//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class cellphonedevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cellphonedevice()
        {
            this.cellphonedeviceForUsers = new HashSet<cellphonedeviceForUser>();
        }
    
        public string CellphonedeviceId { get; set; }
        public string companyId { get; set; }
        public string modelName { get; set; }
    
        public virtual cellphonedeviceCompany cellphonedeviceCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cellphonedeviceForUser> cellphonedeviceForUsers { get; set; }
    }
}
