//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellPhoneDevice_ForNetworks
    {
        public string cellPhoneDeviceNetwork_Id { get; set; }
        public string companyId { get; set; }
        public string networkId { get; set; }
    
        public virtual cellphonedeviceCompany cellphonedeviceCompany { get; set; }
        public virtual Cellularnetwork Cellularnetwork { get; set; }
    }
}
