//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public string userId { get; set; }
        public Nullable<System.DateTime> recommendationDate { get; set; }
        public string cellularnetworkId { get; set; }
        public string locationId { get; set; }
        public string CellphonedeviceId { get; set; }
    }
}
